# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: echo.proto for package 'org.openjproxy.grpc'

require 'grpc'
require 'echo_pb'

module Org
  module Openjproxy
    module Grpc
      module EchoService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'org.openjproxy.grpc.EchoService'

          rpc :Echo, ::Org::Openjproxy::Grpc::EchoRequest, ::Org::Openjproxy::Grpc::EchoResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
