# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto

require 'google/protobuf'


descriptor_data = "\n\necho.proto\x12\x13org.openjproxy.grpc\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Z\n\x0b\x45\x63hoService\x12K\n\x04\x45\x63ho\x12 .org.openjproxy.grpc.EchoRequest\x1a!.org.openjproxy.grpc.EchoResponseB\x14\x42\x10\x45\x63hoServiceProtoP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Org
  module Openjproxy
    module Grpc
      EchoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("org.openjproxy.grpc.EchoRequest").msgclass
      EchoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("org.openjproxy.grpc.EchoResponse").msgclass
    end
  end
end
