# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: StatementService.proto for package 'com.openjproxy.grpc'

require 'grpc'
require 'StatementService_pb'

module Com
  module Openjproxy
    module Grpc
      module StatementService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'com.openjproxy.grpc.StatementService'

          rpc :connect, ::Com::Openjproxy::Grpc::ConnectionDetails, ::Com::Openjproxy::Grpc::SessionInfo
          rpc :executeUpdate, ::Com::Openjproxy::Grpc::StatementRequest, ::Com::Openjproxy::Grpc::OpResult
          rpc :executeQuery, ::Com::Openjproxy::Grpc::StatementRequest, stream(::Com::Openjproxy::Grpc::OpResult)
          rpc :fetchNextRows, ::Com::Openjproxy::Grpc::ResultSetFetchRequest, ::Com::Openjproxy::Grpc::OpResult
          rpc :createLob, stream(::Com::Openjproxy::Grpc::LobDataBlock), stream(::Com::Openjproxy::Grpc::LobReference)
          rpc :readLob, ::Com::Openjproxy::Grpc::ReadLobRequest, stream(::Com::Openjproxy::Grpc::LobDataBlock)
          rpc :terminateSession, ::Com::Openjproxy::Grpc::SessionInfo, ::Com::Openjproxy::Grpc::SessionTerminationStatus
          rpc :startTransaction, ::Com::Openjproxy::Grpc::SessionInfo, ::Com::Openjproxy::Grpc::SessionInfo
          rpc :commitTransaction, ::Com::Openjproxy::Grpc::SessionInfo, ::Com::Openjproxy::Grpc::SessionInfo
          rpc :rollbackTransaction, ::Com::Openjproxy::Grpc::SessionInfo, ::Com::Openjproxy::Grpc::SessionInfo
          rpc :callResource, ::Com::Openjproxy::Grpc::CallResourceRequest, ::Com::Openjproxy::Grpc::CallResourceResponse
          # XA Transaction Operations
          rpc :xaStart, ::Com::Openjproxy::Grpc::XaStartRequest, ::Com::Openjproxy::Grpc::XaResponse
          rpc :xaEnd, ::Com::Openjproxy::Grpc::XaEndRequest, ::Com::Openjproxy::Grpc::XaResponse
          rpc :xaPrepare, ::Com::Openjproxy::Grpc::XaPrepareRequest, ::Com::Openjproxy::Grpc::XaPrepareResponse
          rpc :xaCommit, ::Com::Openjproxy::Grpc::XaCommitRequest, ::Com::Openjproxy::Grpc::XaResponse
          rpc :xaRollback, ::Com::Openjproxy::Grpc::XaRollbackRequest, ::Com::Openjproxy::Grpc::XaResponse
          rpc :xaRecover, ::Com::Openjproxy::Grpc::XaRecoverRequest, ::Com::Openjproxy::Grpc::XaRecoverResponse
          rpc :xaForget, ::Com::Openjproxy::Grpc::XaForgetRequest, ::Com::Openjproxy::Grpc::XaResponse
          rpc :xaSetTransactionTimeout, ::Com::Openjproxy::Grpc::XaSetTransactionTimeoutRequest, ::Com::Openjproxy::Grpc::XaSetTransactionTimeoutResponse
          rpc :xaGetTransactionTimeout, ::Com::Openjproxy::Grpc::XaGetTransactionTimeoutRequest, ::Com::Openjproxy::Grpc::XaGetTransactionTimeoutResponse
          rpc :xaIsSameRM, ::Com::Openjproxy::Grpc::XaIsSameRMRequest, ::Com::Openjproxy::Grpc::XaIsSameRMResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
