# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import StatementService_pb2 as StatementService__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in StatementService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StatementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.connect = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/connect',
                request_serializer=StatementService__pb2.ConnectionDetails.SerializeToString,
                response_deserializer=StatementService__pb2.SessionInfo.FromString,
                _registered_method=True)
        self.executeUpdate = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/executeUpdate',
                request_serializer=StatementService__pb2.StatementRequest.SerializeToString,
                response_deserializer=StatementService__pb2.OpResult.FromString,
                _registered_method=True)
        self.executeQuery = channel.unary_stream(
                '/com.openjproxy.grpc.StatementService/executeQuery',
                request_serializer=StatementService__pb2.StatementRequest.SerializeToString,
                response_deserializer=StatementService__pb2.OpResult.FromString,
                _registered_method=True)
        self.fetchNextRows = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/fetchNextRows',
                request_serializer=StatementService__pb2.ResultSetFetchRequest.SerializeToString,
                response_deserializer=StatementService__pb2.OpResult.FromString,
                _registered_method=True)
        self.createLob = channel.stream_stream(
                '/com.openjproxy.grpc.StatementService/createLob',
                request_serializer=StatementService__pb2.LobDataBlock.SerializeToString,
                response_deserializer=StatementService__pb2.LobReference.FromString,
                _registered_method=True)
        self.readLob = channel.unary_stream(
                '/com.openjproxy.grpc.StatementService/readLob',
                request_serializer=StatementService__pb2.ReadLobRequest.SerializeToString,
                response_deserializer=StatementService__pb2.LobDataBlock.FromString,
                _registered_method=True)
        self.terminateSession = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/terminateSession',
                request_serializer=StatementService__pb2.SessionInfo.SerializeToString,
                response_deserializer=StatementService__pb2.SessionTerminationStatus.FromString,
                _registered_method=True)
        self.startTransaction = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/startTransaction',
                request_serializer=StatementService__pb2.SessionInfo.SerializeToString,
                response_deserializer=StatementService__pb2.SessionInfo.FromString,
                _registered_method=True)
        self.commitTransaction = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/commitTransaction',
                request_serializer=StatementService__pb2.SessionInfo.SerializeToString,
                response_deserializer=StatementService__pb2.SessionInfo.FromString,
                _registered_method=True)
        self.rollbackTransaction = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/rollbackTransaction',
                request_serializer=StatementService__pb2.SessionInfo.SerializeToString,
                response_deserializer=StatementService__pb2.SessionInfo.FromString,
                _registered_method=True)
        self.callResource = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/callResource',
                request_serializer=StatementService__pb2.CallResourceRequest.SerializeToString,
                response_deserializer=StatementService__pb2.CallResourceResponse.FromString,
                _registered_method=True)
        self.xaStart = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/xaStart',
                request_serializer=StatementService__pb2.XaStartRequest.SerializeToString,
                response_deserializer=StatementService__pb2.XaResponse.FromString,
                _registered_method=True)
        self.xaEnd = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/xaEnd',
                request_serializer=StatementService__pb2.XaEndRequest.SerializeToString,
                response_deserializer=StatementService__pb2.XaResponse.FromString,
                _registered_method=True)
        self.xaPrepare = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/xaPrepare',
                request_serializer=StatementService__pb2.XaPrepareRequest.SerializeToString,
                response_deserializer=StatementService__pb2.XaPrepareResponse.FromString,
                _registered_method=True)
        self.xaCommit = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/xaCommit',
                request_serializer=StatementService__pb2.XaCommitRequest.SerializeToString,
                response_deserializer=StatementService__pb2.XaResponse.FromString,
                _registered_method=True)
        self.xaRollback = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/xaRollback',
                request_serializer=StatementService__pb2.XaRollbackRequest.SerializeToString,
                response_deserializer=StatementService__pb2.XaResponse.FromString,
                _registered_method=True)
        self.xaRecover = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/xaRecover',
                request_serializer=StatementService__pb2.XaRecoverRequest.SerializeToString,
                response_deserializer=StatementService__pb2.XaRecoverResponse.FromString,
                _registered_method=True)
        self.xaForget = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/xaForget',
                request_serializer=StatementService__pb2.XaForgetRequest.SerializeToString,
                response_deserializer=StatementService__pb2.XaResponse.FromString,
                _registered_method=True)
        self.xaSetTransactionTimeout = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/xaSetTransactionTimeout',
                request_serializer=StatementService__pb2.XaSetTransactionTimeoutRequest.SerializeToString,
                response_deserializer=StatementService__pb2.XaSetTransactionTimeoutResponse.FromString,
                _registered_method=True)
        self.xaGetTransactionTimeout = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/xaGetTransactionTimeout',
                request_serializer=StatementService__pb2.XaGetTransactionTimeoutRequest.SerializeToString,
                response_deserializer=StatementService__pb2.XaGetTransactionTimeoutResponse.FromString,
                _registered_method=True)
        self.xaIsSameRM = channel.unary_unary(
                '/com.openjproxy.grpc.StatementService/xaIsSameRM',
                request_serializer=StatementService__pb2.XaIsSameRMRequest.SerializeToString,
                response_deserializer=StatementService__pb2.XaIsSameRMResponse.FromString,
                _registered_method=True)


class StatementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def executeUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def executeQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def fetchNextRows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createLob(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readLob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def terminateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def commitTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def rollbackTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def callResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def xaStart(self, request, context):
        """XA Transaction Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def xaEnd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def xaPrepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def xaCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def xaRollback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def xaRecover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def xaForget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def xaSetTransactionTimeout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def xaGetTransactionTimeout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def xaIsSameRM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'connect': grpc.unary_unary_rpc_method_handler(
                    servicer.connect,
                    request_deserializer=StatementService__pb2.ConnectionDetails.FromString,
                    response_serializer=StatementService__pb2.SessionInfo.SerializeToString,
            ),
            'executeUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.executeUpdate,
                    request_deserializer=StatementService__pb2.StatementRequest.FromString,
                    response_serializer=StatementService__pb2.OpResult.SerializeToString,
            ),
            'executeQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.executeQuery,
                    request_deserializer=StatementService__pb2.StatementRequest.FromString,
                    response_serializer=StatementService__pb2.OpResult.SerializeToString,
            ),
            'fetchNextRows': grpc.unary_unary_rpc_method_handler(
                    servicer.fetchNextRows,
                    request_deserializer=StatementService__pb2.ResultSetFetchRequest.FromString,
                    response_serializer=StatementService__pb2.OpResult.SerializeToString,
            ),
            'createLob': grpc.stream_stream_rpc_method_handler(
                    servicer.createLob,
                    request_deserializer=StatementService__pb2.LobDataBlock.FromString,
                    response_serializer=StatementService__pb2.LobReference.SerializeToString,
            ),
            'readLob': grpc.unary_stream_rpc_method_handler(
                    servicer.readLob,
                    request_deserializer=StatementService__pb2.ReadLobRequest.FromString,
                    response_serializer=StatementService__pb2.LobDataBlock.SerializeToString,
            ),
            'terminateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.terminateSession,
                    request_deserializer=StatementService__pb2.SessionInfo.FromString,
                    response_serializer=StatementService__pb2.SessionTerminationStatus.SerializeToString,
            ),
            'startTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.startTransaction,
                    request_deserializer=StatementService__pb2.SessionInfo.FromString,
                    response_serializer=StatementService__pb2.SessionInfo.SerializeToString,
            ),
            'commitTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.commitTransaction,
                    request_deserializer=StatementService__pb2.SessionInfo.FromString,
                    response_serializer=StatementService__pb2.SessionInfo.SerializeToString,
            ),
            'rollbackTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.rollbackTransaction,
                    request_deserializer=StatementService__pb2.SessionInfo.FromString,
                    response_serializer=StatementService__pb2.SessionInfo.SerializeToString,
            ),
            'callResource': grpc.unary_unary_rpc_method_handler(
                    servicer.callResource,
                    request_deserializer=StatementService__pb2.CallResourceRequest.FromString,
                    response_serializer=StatementService__pb2.CallResourceResponse.SerializeToString,
            ),
            'xaStart': grpc.unary_unary_rpc_method_handler(
                    servicer.xaStart,
                    request_deserializer=StatementService__pb2.XaStartRequest.FromString,
                    response_serializer=StatementService__pb2.XaResponse.SerializeToString,
            ),
            'xaEnd': grpc.unary_unary_rpc_method_handler(
                    servicer.xaEnd,
                    request_deserializer=StatementService__pb2.XaEndRequest.FromString,
                    response_serializer=StatementService__pb2.XaResponse.SerializeToString,
            ),
            'xaPrepare': grpc.unary_unary_rpc_method_handler(
                    servicer.xaPrepare,
                    request_deserializer=StatementService__pb2.XaPrepareRequest.FromString,
                    response_serializer=StatementService__pb2.XaPrepareResponse.SerializeToString,
            ),
            'xaCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.xaCommit,
                    request_deserializer=StatementService__pb2.XaCommitRequest.FromString,
                    response_serializer=StatementService__pb2.XaResponse.SerializeToString,
            ),
            'xaRollback': grpc.unary_unary_rpc_method_handler(
                    servicer.xaRollback,
                    request_deserializer=StatementService__pb2.XaRollbackRequest.FromString,
                    response_serializer=StatementService__pb2.XaResponse.SerializeToString,
            ),
            'xaRecover': grpc.unary_unary_rpc_method_handler(
                    servicer.xaRecover,
                    request_deserializer=StatementService__pb2.XaRecoverRequest.FromString,
                    response_serializer=StatementService__pb2.XaRecoverResponse.SerializeToString,
            ),
            'xaForget': grpc.unary_unary_rpc_method_handler(
                    servicer.xaForget,
                    request_deserializer=StatementService__pb2.XaForgetRequest.FromString,
                    response_serializer=StatementService__pb2.XaResponse.SerializeToString,
            ),
            'xaSetTransactionTimeout': grpc.unary_unary_rpc_method_handler(
                    servicer.xaSetTransactionTimeout,
                    request_deserializer=StatementService__pb2.XaSetTransactionTimeoutRequest.FromString,
                    response_serializer=StatementService__pb2.XaSetTransactionTimeoutResponse.SerializeToString,
            ),
            'xaGetTransactionTimeout': grpc.unary_unary_rpc_method_handler(
                    servicer.xaGetTransactionTimeout,
                    request_deserializer=StatementService__pb2.XaGetTransactionTimeoutRequest.FromString,
                    response_serializer=StatementService__pb2.XaGetTransactionTimeoutResponse.SerializeToString,
            ),
            'xaIsSameRM': grpc.unary_unary_rpc_method_handler(
                    servicer.xaIsSameRM,
                    request_deserializer=StatementService__pb2.XaIsSameRMRequest.FromString,
                    response_serializer=StatementService__pb2.XaIsSameRMResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.openjproxy.grpc.StatementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.openjproxy.grpc.StatementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/connect',
            StatementService__pb2.ConnectionDetails.SerializeToString,
            StatementService__pb2.SessionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def executeUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/executeUpdate',
            StatementService__pb2.StatementRequest.SerializeToString,
            StatementService__pb2.OpResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def executeQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/executeQuery',
            StatementService__pb2.StatementRequest.SerializeToString,
            StatementService__pb2.OpResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def fetchNextRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/fetchNextRows',
            StatementService__pb2.ResultSetFetchRequest.SerializeToString,
            StatementService__pb2.OpResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createLob(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/com.openjproxy.grpc.StatementService/createLob',
            StatementService__pb2.LobDataBlock.SerializeToString,
            StatementService__pb2.LobReference.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def readLob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/readLob',
            StatementService__pb2.ReadLobRequest.SerializeToString,
            StatementService__pb2.LobDataBlock.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def terminateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/terminateSession',
            StatementService__pb2.SessionInfo.SerializeToString,
            StatementService__pb2.SessionTerminationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def startTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/startTransaction',
            StatementService__pb2.SessionInfo.SerializeToString,
            StatementService__pb2.SessionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def commitTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/commitTransaction',
            StatementService__pb2.SessionInfo.SerializeToString,
            StatementService__pb2.SessionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def rollbackTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/rollbackTransaction',
            StatementService__pb2.SessionInfo.SerializeToString,
            StatementService__pb2.SessionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def callResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/callResource',
            StatementService__pb2.CallResourceRequest.SerializeToString,
            StatementService__pb2.CallResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def xaStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/xaStart',
            StatementService__pb2.XaStartRequest.SerializeToString,
            StatementService__pb2.XaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def xaEnd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/xaEnd',
            StatementService__pb2.XaEndRequest.SerializeToString,
            StatementService__pb2.XaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def xaPrepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/xaPrepare',
            StatementService__pb2.XaPrepareRequest.SerializeToString,
            StatementService__pb2.XaPrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def xaCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/xaCommit',
            StatementService__pb2.XaCommitRequest.SerializeToString,
            StatementService__pb2.XaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def xaRollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/xaRollback',
            StatementService__pb2.XaRollbackRequest.SerializeToString,
            StatementService__pb2.XaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def xaRecover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/xaRecover',
            StatementService__pb2.XaRecoverRequest.SerializeToString,
            StatementService__pb2.XaRecoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def xaForget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/xaForget',
            StatementService__pb2.XaForgetRequest.SerializeToString,
            StatementService__pb2.XaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def xaSetTransactionTimeout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/xaSetTransactionTimeout',
            StatementService__pb2.XaSetTransactionTimeoutRequest.SerializeToString,
            StatementService__pb2.XaSetTransactionTimeoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def xaGetTransactionTimeout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/xaGetTransactionTimeout',
            StatementService__pb2.XaGetTransactionTimeoutRequest.SerializeToString,
            StatementService__pb2.XaGetTransactionTimeoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def xaIsSameRM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.openjproxy.grpc.StatementService/xaIsSameRM',
            StatementService__pb2.XaIsSameRMRequest.SerializeToString,
            StatementService__pb2.XaIsSameRMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
